### PR TITLE
add item transport

### PR DESCRIPTION
**Pull request by TheEt1234**
Copying message from discord:

# Things that are on zander, unless they really hate doing them:

1) Quests
2) Any potential license issues
3) Textures
4) Recipes
5) Balancing
6) Testing (There will probably be some HUGE bugs)
7) `is the tube size too large? i kinda like it that way tbh`

Most of the code is just code from pipeworks but needlessly and heavily processed thru my brain

### CODE REVIEW

**Comment by TheEt1234** [comment]
(This adds basically the nessesary parts of pipeworks but like i mentioned, needlessly processed thru my brain, thats why it took so long)

**Comment by TheEt1234** [comment]
Also this deprecates the interactor in favour of the puncher, which works on every node, and will work for every node in the future

**Comment by TheEt1234** [comment]
yes berd, i know

**Comment by TheEt1234** [comment]
holy crap the commit list is long....

**Comment by theidealist101** [comment]
> since im so many commits ahead, i now feel like if zander just makes one commit im gonna get bombarded with 50 merge conflicts lmao

lol yeah that's exactly my worry between your PR and mine

**Comment by TheEt1234** [comment]
> > since im so many commits ahead, i now feel like if zander just makes one commit im gonna get bombarded with 50 merge conflicts lmao
> 
> lol yeah that's exactly my worry between your PR and mine

hmmm, which one would be a better idea to merge first

**Comment by theidealist101** [comment]
pretty much just new content

probably yours, since I'm waiting on your change to the quests before I add my quests

**Comment by TheEt1234** [comment]
ah i see

**Pull request merged**
