### PR TITLE
Add dynamic respawn threshold

### PR DESCRIPTION
**Pull request by The4codeblocks**
Changes respawn threshold to be 110m below lowest placed node instead of 110m below the core

### CODE REVIEW

**Comment by TheEt1234** [comment]
ok NOW I GET what you were intending to do, and no, this most likely won't get merged, heres why:

Zander intended the "you fell off the platform" thing to stop mobile players from falling, thinking something is wrong, and leaving his server (back when that was/could be a thing :sob:)

**Comment by The4codeblocks** [comment]
> Zander intended the "you fell off the platform" thing to stop mobile players from falling, thinking something is wrong, and leaving his server (back when that was/could be a thing 😭)

I doubt someone would be crazy enough to go down far enough that the fall duration would be too long
also, the /core tip appears on join

**Comment by TheEt1234** [comment]
ehh ok, we will see what zander thinks /shrug

**Comment by The4codeblocks** [comment]
so..... would it be a good idea to add a command to toggle the safetynet position between current and suggested behavior?

**Comment by TheEt1234** [comment]
> so..... would it be a good idea to add a command to toggle the safetynet position between current and suggested behavior?

Yea, would be nice if it was per-player

**Comment by The4codeblocks** [comment]
> > so..... would it be a good idea to add a command to toggle the safetynet position between current and suggested behavior?
> 
> Yea, would be nice if it was per-player, with a little tip telling you that you can turn this off

@TheEt1234 done

**Comment by The4codeblocks** [comment]
> Oh, I'm in class so I didn't read the code lol, I can merge it RN if it's ready?

yeh, it's ready

**Pull request merged**
