### PR TITLE
Improve quests (and maybe other miscellanous stuff)

### PR DESCRIPTION
**Pull request by birdlover32767**
this pr changes the wording (and typos) on quests, as well as other misc stuff

### CODE REVIEW

**Comment by ChefZander** [comment]
I probably wont merge hiding unavailable quests like that. Please update that.
Also, join the Skyblock Zero discord server, it's where we coordinate what changes should be made or not, so no unnecessary work gets done.
Here's the invite: https://discord.gg/TrPW9knB

- Zander

**Comment by birdlover32767** [comment]
i don't have a discord due to age reasons but sure i could update the hidden thing

**Comment by birdlover32767** [comment]
also i just noticed mercury dust shouldn't exist

mercury is a _liquid_ it's more fit for the _fluid cells_

**Comment by TheEt1234** [comment]
@ChefZander dont trust chatgpt with chemistry that much

**Comment by TheEt1234** [comment]
@ChefZander dont trust chatgpt with chemistry that much

**Comment by ChefZander** [comment]
This completely broke the questbook. Amazing.

**Comment by theidealist101** [comment]
> also i just noticed mercury dust shouldn't exist
> 
> mercury is a _liquid_ it's more fit for the _fluid cells_

aha but we're in space, therefore cold... that's my excuse

**Comment by ChefZander** [comment]
You dont know the temperature of *my* space!

**Comment by birdlover32767** [comment]
so if space is cold enough to have solid mercury then the plants also have to be in a greenhouse or just really weird

**Comment by ChefZander** [comment]
Yes, *in the discord*, we planned the plants to be grown under glass domes with watering systems, oxygen production and temperature stabilizers, of sorts.

**Comment by TheEt1234** [comment]
@birdlover32767 the plants will be blessed by the spagetti monster

**Comment by ChefZander** [comment]
What

**Comment by birdlover32767** [comment]
so wait that means the fluid cells are either infused with spaghetti monster essence or just somehow hot
(the water one)

**Comment by ChefZander** [comment]
The casing is so strong that the pressure cant break the container and is forced to stay liquid.

**Comment by birdlover32767** [comment]
also if the disembodied trail player is in space how do they still have a bit of gravity
does the core make gravity? if so, why doesn't the player go to the center instead of down

**Comment by birdlover32767** [comment]
also it would be nice if i actually saw the discord because the only thing i know is greenhouse

**Comment by TheEt1234** [comment]
> also it would be nice if i actually saw the discord because the only thing i know right now is greenhouse

zander is planning to make a discord<->mt bridge but thats most likely not going to solve your problem

**Comment by birdlover32767** [comment]
what if i just use you as a discord bridge

**Comment by theidealist101** [comment]
just join the discord lol

**Comment by birdlover32767** [comment]
i'm too young for the discord tos or whatever

**Comment by birdlover32767** [comment]
also because switching stations exist now all machine crafts should be buffed to have like emittrium

**Comment by ChefZander** [comment]
this is not legal advice but lying about your age is a real thing, and you can do that

**Comment by birdlover32767** [comment]
nah i'd be better safe than sorry

**Comment by ChefZander** [comment]
safe from what

**Comment by birdlover32767** [comment]
excessive amounts of accounts

**Comment by ChefZander** [comment]
youre fine as long as you dont tell people lmao

**Comment by birdlover32767** [comment]
what if they see this thread

**Comment by ChefZander** [comment]
discord? lmao why would they see this they have 150 million monthly active users

**Comment by birdlover32767** [comment]
but it just doesn't sit right with me

**Pull request merged**
