### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by TheEt1234**

### CODE REVIEW

**Comment by TheEt1234** [comment]
(probably needs some bugtesting)

**Comment by TheEt1234** [comment]
Possible balance issues

# Antimatter generator
- requires 1 matter and 1 antimatter/s (effectively 2 matter/s + 1 core dust/s)
- generates 120 power

**Comment by TheEt1234** [comment]
oh yeah i forgot to add some sick particles to the antimatter generator

**Comment by TheEt1234** [comment]
To sum up the update:
- added protections
- added 2 protectors
- added high power electric furnace
- reworked the way chemicals are registered, to allow for ingots
  - change the recipe of everything to use ingots instead of dusts
- fix a couple bugs and inconveniences

**Comment by TheEt1234** [comment]
oh wait i think i forgot about public storinators completely

**Comment by TheEt1234** [comment]
well i guess i will just put nodestates here?

**Comment by TheEt1234** [comment]
ok i did

**Comment by TheEt1234** [comment]
that was a bad idea holdon

**Comment by birdlover32767** [comment]
i feel like the protections and public storinates should only be available in multiplayer

**Comment by TheEt1234** [comment]
> i feel like the protections and public storinators should only be available in multiplayer

there was a discussion and yeah no, a server owner can prepare a world in singleplayer creative first then make a server

**Comment by TheEt1234** [comment]
actually nvm this is totally fine, i cant reproduce the freeze bug

**Comment by TheEt1234** [comment]
nvm i can reproduce it... crap

**Comment by TheEt1234** [comment]
and now i cant reproduce it... is minetest trolling me

**Comment by TheEt1234** [comment]
yeah ok idk what that entire thing was,

but basically, reproduction steps:

1) have a stateful machine be active in a switching station network
2) delete the switching station
3) maybe it will freeze the game??

**Comment by TheEt1234** [comment]
but it doesnt do that anymore

**Pull request merged**
