### PR TITLE
Logic item transport

### PR DESCRIPTION
**Pull request by TheEt1234**
# i need feedback on this

### CODE REVIEW

**Comment by TheEt1234** [comment]
API:
```lua
local e = yield({
   type = "transport_items",
   from = links.input,
   to = links.output, 
   filters = {
     groups = { powder = 1}
    },
    inv_list_outputs = "main", -- optional
    inv_list_inputs = "main", -- optional
})
```

**Comment by TheEt1234** [comment]
i think its fine

**Comment by birdlover32767** [comment]
btw idea: ram sticks grant +10% more memory per stick for a luacontroller (with a max of 4 ram sticks)

**Comment by TheEt1234** [comment]
> btw idea: ram sticks grant +12.5% more memory per stick for a luacontroller (with a max of 4 ram sticks)

internally, it's named 1kb ram stick, so yea, 1kb, with 4 ram sticks being 4kb, i think thats good, ill do that later (im working on ladders right now, they are going to be the best ladders in minetest)

**Comment by birdlover32767** [comment]
well ik but a luacontroller's memory capacity varies based on settings (and i think the default is 1mb so...)

**Comment by TheEt1234** [comment]
> well ik but a luacontroller's memory capacity varies based on settings (and i think the default is 1mb so...)

oh... i thought i made it 1kb lol
but yea `is 1024*1024 bits a megabyte or a kilobyte`

**Comment by birdlover32767** [comment]
1024 BYTES are a kiloBYTE
1024*1024 BYTES are a megaBYTE

1024 BITS are 0.125 kiloBYTEs or 128 BITS
1024*1024 BITS are 0.125 megaBYTEs or 128 kiloBYTEs

**Comment by TheEt1234** [comment]
yeah so im counting bytes, so that "1kb" ram stick is actually 1 megabyte ram stick.... i was wrong by an order of magnitude, oops

**Comment by birdlover32767** [comment]
you know lead exists (but it's disabled rn)

also what about that neutronium
will you make a neutronium maker that makes neutrons out of charged particles, core dust, emittrium or whatever
or is the neutronium just extremely compressed matter

**Comment by TheEt1234** [comment]
> you know lead exists (but it's disabled rn)
> 
> also what about that neutronium
> will you make a neutronium maker that makes neutrons out of charged particles, core dust, emittrium or whatever
> or is the neutronium just extremely compressed matter

Welll, you get neutronium from the meteorite that the meteorite maker made

**Comment by birdlover32767** [comment]
i was talking about the neutronium in the meteorite that the meteorite maker made

**Pull request merged**
