### PR TITLE
STAIRS (and cnc machine)

### PR DESCRIPTION
**Pull request by TheEt1234**

### CODE REVIEW

**Comment by birdlover32767** [comment]
also it would be very funny if you could cut every node with the cnc

air slab
alloy furnace stairs
core inner stairs

**Comment by TheEt1234** [comment]
> also it would be very funny if you could cut every node with the cnc
> 
> air slab alloy furnace stairs core inner stairs
table.foreach(minetest.registered_nodes, stairs.register)

(dont use table.foreach in prod or at least polyfill it)

**Comment by TheEt1234** [comment]
ok, i will have to add

quests for lights
quest for leveled tool
and the leveled tool texture

**Comment by TheEt1234** [comment]
ok so i optimized and cleared up a bunch of stuff

**Comment by TheEt1234** [comment]
Changes:
- added the cnc machine, which can make stairs out of certain blocks
- added powered lights, super powered light
- added colorium tree, which is, yea, a tree
- added colorium and the coloring tool, those can be used to color certain blocks with like a lot of colors
- Made pump, switching station code less messy
- Made habitat regulators 2x more performant
- Fixed the bug where if you have more than 1 habitat regulator it would like make plants grow faster

**Comment by TheEt1234** [comment]
@ChefZander  i think its ok to merge, i will work on `minetest.d.lua` in the meantime

**Comment by birdlover32767** [comment]
* add eggcorns

**Pull request merged**
