### PR TITLE
***LOGIC***

### PR DESCRIPTION
**Pull request by TheEt1234**
yea

### CODE REVIEW

**Comment by TheEt1234** [comment]
feel free to test for holes/crash/memory bugs

**Comment by TheEt1234** [comment]
as of now... the logic is kinda(?) useless, currently serves as a ***SUPER COMPLEX*** decorating block... as it can only change itself or other luacontrollers

**Comment by TheEt1234** [comment]
(not a single merge conflict... wow)

**Comment by birdlover32767** [comment]
sbz_logic/sandbox.lua crashed at line 111 because env.links is nil (i suggest adding a `or {}` to the end of line 110)

anyways the editor disc doesnt work

**Comment by TheEt1234** [comment]
> sbz_logic/sandbox.lua crashed at line 111 because env.links is nil (i suggest adding a `or {}` to the end of line 110)
> 
> anyways the editor disc doesnt work

Thanks, fixed both

**Comment by birdlover32767** [comment]
also uh why isnt print defined

**Comment by TheEt1234** [comment]
> also uh why isnt print defined
> 
> btw a sort of docs mod (not qb - that is for guiding the player) (yes i know info_extra exists but do you think fitting groups, inventories, whatever is good) would be useful (wait actually some sort of documentation node that can grab info with lua thingies)

you use the `terminal_text` (global) variable to print to terminal text, 
explanation: the basic editor sees that `terminal_text` in your coroutine envinronment and simply yeah sets the terminal tab to that

as to why i didn't define print.... well... the editor could define `print` by modifying the code, but that's just something that my mind hasn't thought about at that time, and, afterall, you are supposed to make your own better editor, so think of it as motivation :D

as for the docs, yeah, OBVIOUSLY i can't shove the entire luacontroller documentation into the questbook, so yeah i will create some kind of knowledge station, that would be used to craft the doc book and the system disks

**Comment by birdlover32767** [comment]
the knowledge station should give info about other nodes as well imo (like the % of the core dropping matter dust)

**Comment by TheEt1234** [comment]
sure

**Comment by birdlover32767** [comment]
wait so you added unified inventory
there goes my crafting guide problems

**Comment by TheEt1234** [comment]
> wait so you added unified inventory there goes my crafting guide problems

yea

**Comment by TheEt1234** [comment]
ive heavily modified it

**Comment by TheEt1234** [comment]
and also added like all the crafts

**Comment by TheEt1234** [comment]
things planned:
- ele fab (shamelessly borrowed idea from techage)
- knowledge station (place where you can craft system disks and tutorials)

**Comment by TheEt1234** [comment]
this update is like 30% finished lol

**Comment by TheEt1234** [comment]
oh no...
image

**Comment by birdlover32767** [comment]
forget abt the ele fab
make the 4x4 crafting station bcz why not (and modify unified inventory)

**Comment by TheEt1234** [comment]
> forget abt the ele fab
> make the 4x4 crafting station bcz why not (and modify unified inventory)

4x4 crafting for crafting logic stuffs, ele fab for things like luanium, lua chip, LEDs

**Comment by birdlover32767** [comment]
the fun part is that you can extend the 4x4 crafting into NxN crafting for basically infinite (but repetitive) content

but it should only go up to 5x5 imo

**Comment by birdlover32767** [comment]
btw you cant un-compress compressed core dust

**Comment by birdlover32767** [comment]
also: starlight collectors still make particles even if they don't have a connected network/inactive

they also generate energy (and make particles) if there is an opaque block above

**Comment by TheEt1234** [comment]
> ALSO the power pipes show a bit of yellow when mined/seen from far away with mipmaps enabled
oh yea i made the corners yellow because i was experimenting with it being yellow and just didnt bother to remove it

**Comment by birdlover32767** [comment]
yeah i saw that in the power pipe texture

**Comment by TheEt1234** [comment]
btw what should luanium be crafted out of (im adding an ele fab)

**Comment by theidealist101** [comment]
probably like emittrium and something else (maybe a plant or a meteorite drop or something?)

**Comment by TheEt1234** [comment]
or maybe i should add silicon

**Comment by TheEt1234** [comment]
i dont like adding chemicals but silicon honestly just makes sense to add

**Comment by TheEt1234** [comment]
im thinking 8 silicon + 8 reinforced matter blob => luanium, is that fair

**Comment by TheEt1234** [comment]
or now that i think about it...

8 silicon + 8 emittrium circuits => luanium
4 luanium + matter plate => lua chip

**Comment by TheEt1234** [comment]
now im wondering whats next... maybe a "linker core" (crafted from warp shroom and 8 core dust)

Linker core: 1 shroom, 8 compressed core dust

Link tool: 2 matter dust + 1 linker core
Link upgrade: link tool + luacontroller upgrade template
(new) Power efficency upgrade: 8 invar powder + luacontroller upgrade template (Max: 3)
and with it also increase by default power consumbtion by 4x 

Luacontroller upgrade template: 
         |      nikel
nikel | emittrium circuit|  nikel
          |  nikel
 
 The luacontroller itself:
 luanium chip |  luanium chip | luanium chip
luanium chip | neutronium | luanium chip
 luanium chip |  storinator | luanium chip
 
 Knowledge station:
stone | stone                           | stone
stone | simple charged field | stone
stone | stone                            | stone

**Comment by birdlover32767** [comment]
<details>
<summary>if you want intense microcrafting:</summary>

8 silicon + 4 emittrium circuits => luanium
2 luanium + 2 emittrium circuit + 1 simple circuit => lua circuit

-----------------------

tungsten can be obtained from grinding pebbles/meteoric metal
tungsten needs 2 powder to smelt into 1 ingot

powder now smelts to lumps

tungsten lump = tl, rf = reinforced matter

tl tl tl
.  rf      => hammer
.  rf

.......................... hammer
copper lump copper lump copper lump => copper plate

copper plate copper plate copper plate
                                                           => wire mold
copper plate copper plate copper plate

rf rf rf
rf .   rf => molder
tl hpef tl

molder has 2 inv slots for mold and metal

mold + silver + wire mold => silver wire

2 lua circuits + silver wire + 2 luanium => lua chip
1 simple circuit + 1 retaining circuit + 3 lua chips + silver wire => luac
</details>

**Comment by birdlover32767** [comment]
idea: the knowledge station can give more information/tips about other nodes as well

example: if you're too lazy to add a punching recipe then you can put "10% chance of dropping emittrium, ..." into the knowledge station

**Comment by birdlover32767** [comment]
also, api.lua never gets run (in unified inventory)

**Comment by TheEt1234** [comment]
> also, api.lua never gets run (in unified inventory)

if it doesn't run then the game would implode 5 times over what are you talking about

**Comment by birdlover32767** [comment]
wait it still implodes

**Comment by birdlover32767** [comment]
Capture
what went wrong

**Comment by TheEt1234** [comment]
> Capture
> 
> what went wrong

does unified inventory have a .git folder

if so, reinstall the entire game

**Comment by TheEt1234** [comment]
yea it works for me, its probably because you cloned it at a time where the unified inventory had a .git folder (aka was a submodule)

**Comment by TheEt1234** [comment]
> idea: the knowledge station can give more information/tips about other nodes as well
> 
> example: if you're too lazy to add a punching recipe then you can put "10% chance of dropping emittrium, ..." into the knowledge station
> 
> also it still doesnt work

ok what

**Comment by TheEt1234** [comment]
wait, what doesnt work specifically

**Comment by TheEt1234** [comment]
for me the crusher works perfectly

**Comment by birdlover32767** [comment]
crusher tries to call unified_inventory.get_usage_list but it's not defined (apparently)
keep in mind this error occures in-game aka not when mods are loaded

**Comment by TheEt1234** [comment]
> crusher tries to call unified_inventory.get_usage_list but it's not defined (apparently) keep in mind this error occurs in-game aka not when mods are loaded

Run this with worldedit, if it returns `<function>` something more deeply wrong is happening, if it returns nil, unified inventory hasn't loaded propertly, or the vanilla version of the unified inventory is being used

image


And also screenshot your version of the unified inventory, it should look like this:
image

**Comment by TheEt1234** [comment]
> Capture yeah...

and the crusher still doesn't work?

**Comment by TheEt1234** [comment]
what item did you put in

**Comment by birdlover32767** [comment]
pebbles

**Comment by TheEt1234** [comment]
> pebbles, probably
> 
> the game crashes faster than i can see the crusher tho

yea they work for me, try using the crusher in your new world

**Comment by birdlover32767** [comment]
it works in the new world, odd

**Comment by TheEt1234** [comment]
> it works in the new world, odd

ok thats really odd

**Comment by birdlover32767** [comment]
idea: a warning if skyblock_zero is running on a server without libox in trusted mods

**Comment by TheEt1234** [comment]
> idea: a warning if skyblock_zero is running on a server without libox in trusted mods
> 
> also the knowledge station should be able to give info about everything e.g you put luacontroller in its input, you get it back and you get the pages on logic example 2: core dust in, core loot chances out (33% matter dust, 33% charged particle, 33% core dust)

I think i want to just keep it for logic, for now

Also, https://github.com/TheEt1234/libox/blob/f2107bfd68c3b3c49f1c9fb7aa67d8c390c178d7/init.lua#L3

**Comment by birdlover32767** [comment]
nice and okay then

**Comment by birdlover32767** [comment]
okay wait why is every recipe registered twice (well as i see it in the craftguide)

**Comment by TheEt1234** [comment]
> okay wait why is every recipe registered twice (well as i see it in the craftguide)
> 
> also this looks weird Capture

im back, and yeah i wanted the texture to be seperate (because unified inventory had it originaly seperate) but yeaaa ok i will fix it

**Comment by TheEt1234** [comment]
also crafts for me work normally (works on my machine :D), could you screenshot your unified inventory

**Comment by TheEt1234** [comment]
now... what will be the plan foward, should i add upgrades+disks pipeworks support to the luacontroller?

Or should i add an entire sfm-like system for luacontrollers?
Or should that be the next update?

Should i add an in-world display too? (And a formspec display)

Either way i need to add more recipes, ram, and better textures

**Comment by ChefZander** [comment]
> idea: the knowledge station can give more information/tips about other nodes as well
 the.... questbook??

**Comment by TheEt1234** [comment]
> > idea: the knowledge station can give more information/tips about other nodes as well
> 
> the.... questbook??

no
image

**Comment by TheEt1234** [comment]
now im a bit puzzled about the system disks....

**Comment by TheEt1234** [comment]
@birdlover32767 can i make antimatter blobs and antimatter things in general NOT explode when matter things are near them, its really really annoying

**Comment by TheEt1234** [comment]
i think this is ready

**Comment by TheEt1234** [comment]
all thats left to do is trace down the very very weird freeze bug... (which has been here before logic) but i think ill do that next time

**Comment by TheEt1234** [comment]
and waait.... *should* i add quests?

**Comment by TheEt1234** [comment]
ok now it should be fine

**Comment by birdlover32767** [comment]
yes you can, just remove the "Annihilate matter and antimatter" abm or whatever it was called in sbz_resources/nodes.lua

**Review by birdlover32767 — COMMENTED** [review]
why did you remove unbreakable from creative hand caps
also idk how this review stuff works but ill work it out

**Comment by TheEt1234** [comment]
> why did you remove unbreakable from creative hand caps also idk how this review stuff works but ill work it out

because why have it there... if you are going to remove emitters or cores, use worldedit for that

**Comment by TheEt1234** [comment]
also birdlover did you manage to reproduce the "random infinite loop" bug

**Comment by birdlover32767** [comment]
i havent seen it (i need to test logic more but idk the functions for links)

**Comment by TheEt1234** [comment]
i think this is merge-able @ChefZander

**Pull request merged**
